services:
  web:
    container_name: web
    image: web:latest
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      FASTCGI_PASS: app
      TZ: ${TZ}
      LANG: ${LANG}
    depends_on:
      app:
        condition: service_healthy
    working_dir: /var/www/html
  app:
    container_name: app
    image: app:latest
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      TZ: ${TZ}
      LANG: ${LANG}
    depends_on:
      db:
        condition: service_healthy
    working_dir: /var/www/html
  db:
    container_name: db
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: ${TZ}
      LANG: ${LANG}
    restart: always
    volumes:
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: [
              "CMD-SHELL",
              "mysql -h $${MYSQL_HOST} -u $${MYSQL_USER} -p$${MYSQL_PASSWORD} -P$${MYSQL_PORT} -e 'show databases'"
            ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
